### ISSUE TITLE
GTEx analysis seems to be broken

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/biojupies#30] opened 2018-10-05 18:11 UTC
Selected 20-29 old and not exposed skin in group 1 and 20-29 exposed skin in group 2, click continue... ended back in the starting page.

**Comment by denis-torre** [comment] 2018-10-05 19:42
This happens when the user filters the table, but does not actually select any sample with the provided checkboxes.

The issue is now fixed. Instead of redirecting, the user will receive a warning to select at least two samples per group.

**Closed by denis-torre** 2018-10-05 19:42 UTC
Labels: bug
